services:
  server:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=dbpass

    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass

  redis:
    image: redis:7.0.10-alpine
    hostname: redis

  celery:
    build:
      context: .
    hostname: celery
    command: celery -A service.celery.app celery -l info
    volumes:
      - ./service:/service
    links:
      - redis
    depends_on:
      - redis