services:
  server:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=dbpass

    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass

  redis:
    image: redis:7.0.10-alpine
    hostname: redis

  celery:
    build:
      context: .
    command: celery -A service.celery.app worker -l info
    volumes:
      - ./service:/service
    depends_on:
      - redis
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=dbpass


  celery2:
    build:
      context: .
    command: celery -A service.celery.app worker -l info
    volumes:
      - ./service:/service
    depends_on:
      - redis
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=dbpass

  flower:
    build:
      context: .
    command: celery -A service.celery.app flower
    volumes:
      - ./service:/service
    depends_on:
      - celery
    ports:
      - "5555:5555"


